### ISSUE TITLE
Can we remove this repository?

### ISSUE THREAD

**Issue by buren** [justarrived/just-style#1]
@pstenstrm can we remove this repository?

Or this perhaps still a good starting point for a style guide? (I like the idea)

**Comment by pstenstrm** [comment]
If you want to remove it it's OK by me.

I always think it's good to have a style guide, as long as it can be kept up to date.

**Comment by buren** [comment]
@pstenstrm yeah I totally agree 👍 Is the scripts/dev environment etc working? If so I think we should keep this :)

**Comment by pstenstrm** [comment]
Yes, everything is working.

Though of course none of the style/markup is aligned with what's actually on the site

**Comment by buren** [comment]
Cool 😎 Lets keep it, after release we can "port" the styles from the app here.
